language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
#cache: cargo
before_script:
  - cargo install --force cargo-when
  - cargo install --force cargo-audit
script:
  # Tests should run on all supported rustc versions
  - cargo test --tests --examples
  - cargo test --doc
  - cargo test --all-features
  # Blocking reqwest using reqwest 0.9
  - cargo test --tests --examples --features reqwest-09 --no-default-features
  # Futures 0.1 with reqwest 0.9
  - cargo test --tests --examples --features reqwest-09,futures-01 --no-default-features
  # Futures 0.1 without reqwest (examples will not build)
  - cargo test --tests --features futures-01 --no-default-features
  # Futures 0.3 with reqwest 0.10
  - cargo test --tests --examples --features futures-03,reqwest-010 --no-default-features
  # Futures 0.3 without reqwest (examples will not build)
  - cargo test --tests --features futures-03 --no-default-features
  # Futures 0.3 with reqwest 0.9 (included by default)
  - cargo test --tests --examples --features futures-03
  - cargo audit
notifications:
  email:
    on_success: never
